# Ken Henderson
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: https://www.kenhendersonm.me

# Title of the Site
title: Ken Henderson
# Description of the Site
description: Professional Services & Software Operations
# URL of Image of the Site
site-image: "assets/images/ken-henderson-revconf.jpg"
# Keywords of the Site
site-keywords: Business Operations,Operations,Professional Services,Software Operations,Delivery Operations 
# URL for the Image of custom Favicon
favicon-url: ""

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: henderson.ken@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: 
github_username:  

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: "../images/ken-henderson-revconf.jpg"
# Google Analytics
google-analytics: ""

# Name of the Author
author-name: Ken Henderson
# URL for the Image of the Author
author-image: "assets/images/ken.png"
# 60 Words About the Author
author-about: I have a passion for end-to-end business operations, and have built and evolved all core processes (lead-to-opportunity, opportunity-to-cash, hire-to-retire, you name it) in companys that range from 3 people to over 115,000 people.....and I love every bit it. Although I spent the better part of my career in professional services, I've grown to enjoy leading both professional services and software development companies. On the "Builder <--> Operator" spectrum, I probably lean towards the builder side, as I very-much enjoy building and finding new ways to optimize. I welcome opportunities to share experiences (and perhaps enjoy sharing a cold beer or cup of coffee) colleagues and leaders alike, but also enjoy giving back and mentoring the next generation.

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
